# Generated by Django 5.0.4 on 2024-04-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.CharField(max_length=20)),
                ('product_photo', models.FileField(upload_to='ProductPhoto/')),
                ('product_stock', models.IntegerField(default=0)),
                ('product_discription', models.CharField(max_length=500)),
                ('scategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_scategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.FileField(upload_to='Product_Photos/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
            ],
        ),
    ]
