# Generated by Django 5.0.4 on 2024-04-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queries_name', models.CharField(max_length=20)),
                ('queries_email', models.CharField(max_length=20)),
                ('queries_message', models.CharField(max_length=500)),
                ('queries_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=20)),
                ('coach_email', models.CharField(max_length=20)),
                ('coach_contact', models.CharField(max_length=20)),
                ('coach_gender', models.CharField(max_length=20)),
                ('coach_dob', models.CharField(max_length=20)),
                ('coach_address', models.CharField(max_length=50, null=True)),
                ('coach_photo', models.FileField(upload_to='CoachDoc/')),
                ('coach_licence', models.FileField(upload_to='Coachlic')),
                ('coach_password', models.CharField(max_length=20)),
                ('coach_vstatus', models.CharField(default='0', max_length=1, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_event')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=20)),
                ('shop_email', models.CharField(max_length=20)),
                ('shop_contact', models.CharField(max_length=20)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_photo', models.FileField(upload_to='Shopphoto/')),
                ('shop_proof', models.FileField(upload_to='Shopproof/')),
                ('shop_password', models.CharField(max_length=20)),
                ('shop_vstatus', models.CharField(default='0', max_length=1)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_gender', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=500)),
                ('user_dob', models.CharField(max_length=20)),
                ('user_photo', models.FileField(upload_to='Userphoto/')),
                ('user_proof', models.FileField(upload_to='Userproof/')),
                ('user_password', models.CharField(max_length=20)),
                ('user_vstatus', models.CharField(default='0', max_length=20, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('coach_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_from', to='Guest.tbl_coach')),
                ('coach_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_to', to='Guest.tbl_coach')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=500)),
                ('complaint_content', models.CharField(max_length=500)),
                ('comaplaint_replay', models.CharField(max_length=500, null=True)),
                ('comaplaint_status', models.CharField(default=0, max_length=1, null=True)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_coach')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
